name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  windows:
    name: Windows (Java 17)
    runs-on: windows-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build & Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build test -PskipSpotless
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Upload Test Report
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: windows-test-report
          path: jsvg/build/reports
      - name: Upload Test Diffs
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: windows-test-diffs
          path: build/ref_test

  macOS:
    name: MacOS (Java 17)
    runs-on: macos-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build & Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build test -PskipSpotless
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Upload Test Report
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: macos-test-report
          path: jsvg/build/reports
      - name: Upload Test Diffs
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: macos-test-diffs
          path: build/ref_test

  linux:
    name: Linux (Java 17)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build & Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build test -PskipSpotless
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Upload Test Report
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: linux-test-report
          path: jsvg/build/reports
      - name: Upload Test Diffs
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: linux-test-diffs
          path: build/ref_test
